# conda env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cookiecutter
  - pygments
  - jupyter
  - jupyterlab
  - python={{ cookiecutter.python_version }}